export const userActions = {
	SET_LOGIN: "SET_LOGIN",
	UNSET_LOGIN: "UNSET_LOGIN",
	SET_LOGIN_ERROR: "SET_LOGIN_ERROR"
}
export default {
	ACTION_TYPE_1: "ACTION_TYPE_1",
	SIMPLE_ACTION: "SIMPLE_ACTION",
	SIMPLE_ACTION_WITH_PAYLOAD: "SIMPLE_ACTION_WITH_PAYLOAD",
	ASYNC_ACTION_TOGGLE: "ASYNC_ACTION_TOGGLE",
	ASYNC_ACTION_SUCCESS: "ASYNC_ACTION_SUCCESS",
	ASYNC_ACTION_FAILURE: "ASYNC_ACTION_FAILURE"
}